### ISSUE TITLE
Convert Location Data to JSON or KML

### ISSUE THREAD

**Issue by dwcaraway** [codefordayton/esl#1]
Leigh created a map at https://mapsengine.google.com/map/u/0/edit?mid=zC9ScMhT9H4s.kMymDCCmlwEU. Need the data point information captured so that it can be rendered on the application.

**Comment by raudabaugh** [comment]
It might be a good idea for Leigh to post the CSV on here somewhere, maybe as a gist?

**Comment by DavidEBest** [comment]
There are some JS libraries for parsing CSVs. Do we want to keep things in that format for the sake of simplicity for the government folks to update, or not worry about it for the time being?

We can geocode the points using a free service like http://www.gpsvisualizer.com/geocoder/ and just update our data by hand for now.

If/when we need to geocode on the fly, Yahoo's YQL interface is pretty slick.

**Comment by raudabaugh** [comment]
My vote would be to go with GeoJSON, since Leaflet seems to prefer them,
and Github is starting to do some cool stuff with diffing them and such (
https://github.com/blog/1772-diffable-more-customizable-maps).
As far as simplicity for government folks updating, we could either point
them to this service - http://geojson.io - or just build a good CSV parser.  I
made one in Python a while back that does Yahoo geocoding, need to find it and
dust it off.

**Comment by raudabaugh** [comment]
Here is the CSV that Leigh made:
https://gist.github.com/raudabaugh/8853334

**Comment by DavidEBest** [comment]
I cleaned up the data a bit and added lat/lons.

https://gist.github.com/DavidEBest/8855745

**Comment by dwcaraway** [comment]
@DavidEBest Can this be closed now?
